#!/usr/bin/env python3
"""
Run 2 RL agents on gen9randombattle format on local Pokemon Showdown server.
For random battles, teams are auto-generated by the server, so we don't specify a team_set.
"""

import os
import asyncio
from metamon.rl.pretrained import get_pretrained_model

# Set cache directory
os.environ['METAMON_CACHE_DIR'] = os.path.join(os.path.dirname(__file__), '.metamon_cache')

async def run_agent_on_ladder(agent_name: str, username: str, num_battles: int = 10):
    """
    Run a single agent on the gen9randombattle ladder.

    Args:
        agent_name: Name of the pretrained model (e.g., 'Abra', 'SmallRLGen9Beta')
        username: Unique username for this agent
        num_battles: Number of battles to play
    """
    print(f"\n{'='*60}")
    print(f"Starting {agent_name} as '{username}' on gen9randombattle")
    print(f"{'='*60}\n")

    # Get the pretrained model
    pretrained_model = get_pretrained_model(agent_name)

    # Initialize the agent
    agent = pretrained_model.initialize_agent(checkpoint=None, log=False)
    agent.env_mode = "sync"
    agent.parallel_actors = 1
    agent.verbose = True

    # Import the ladder environment maker
    from metamon.rl.metamon_to_amago import make_local_ladder_env

    # Create the ladder environment for gen9randombattle
    # Note: Random battles don't use a team_set since teams are auto-generated
    make_env = lambda: make_local_ladder_env(
        observation_space=pretrained_model.observation_space,
        action_space=pretrained_model.action_space,
        reward_function=pretrained_model.reward_function,
        num_battles=num_battles,
        player_username=username,
        player_avatar="red-gen1main",
        player_team_set=None,  # No team set needed for random battles
        battle_backend="poke-env",
        battle_format="gen9randombattle",
        save_trajectories_to=None,
        save_team_results_to=None,
    )

    # Run the evaluation
    results = agent.evaluate_test(
        [make_env],
        timesteps=num_battles * 1000,
        episodes=num_battles,
    )

    print(f"\n{'='*60}")
    print(f"Results for {username}:")
    print(f"{'='*60}")
    print(results)
    print()

    return results


async def main():
    """Run 2 agents in parallel on gen9randombattle"""

    # Choose agents - using Gen 9 compatible models
    agent1_model = "Abra"  # Medium-sized Gen 9 model
    agent2_model = "Minikazam"  # Small RNN Gen 9 model

    num_battles = 20  # Number of battles per agent

    print("""
╔════════════════════════════════════════════════════════════╗
║  Running 2 RL Agents on gen9randombattle                  ║
║                                                            ║
║  Agent 1: Abra (as 'MetamonAgent1')                       ║
║  Agent 2: Minikazam (as 'MetamonAgent2')                  ║
║                                                            ║
║  They will queue for random battles on the local ladder   ║
║  and may battle each other or other connected players.    ║
╚════════════════════════════════════════════════════════════╝
    """)

    # Note: Since we're using the same event loop, we'll run them sequentially
    # To run truly in parallel, we'd need to use multiprocessing
    print("NOTE: Agents will run sequentially due to asyncio constraints.")
    print("To run them simultaneously, launch this script in 2 separate terminals with different usernames.\n")

    # Run agent 1
    results1 = await run_agent_on_ladder(
        agent_name=agent1_model,
        username="MetamonAgent1",
        num_battles=num_battles
    )

    # Run agent 2
    results2 = await run_agent_on_ladder(
        agent_name=agent2_model,
        username="MetamonAgent2",
        num_battles=num_battles
    )

    print("\n" + "="*60)
    print("FINAL RESULTS")
    print("="*60)
    print(f"\nAgent 1 ({agent1_model} as MetamonAgent1):")
    print(results1)
    print(f"\nAgent 2 ({agent2_model} as MetamonAgent2):")
    print(results2)
    print()


if __name__ == "__main__":
    asyncio.run(main())
