#!/usr/bin/env python3
"""
Run a single RL agent on gen9randombattle format on local Pokemon Showdown server.
This script can be run multiple times in parallel with different arguments.
"""

import os
import sys
import argparse

# Set cache directory
os.environ['METAMON_CACHE_DIR'] = os.path.join(os.path.dirname(__file__), '.metamon_cache')

from metamon.rl.pretrained import get_pretrained_model
from metamon.rl.metamon_to_amago import make_local_ladder_env


def run_agent(agent_name: str, username: str, num_battles: int = 20):
    """
    Run a single agent on the gen9randombattle ladder.

    Args:
        agent_name: Name of the pretrained model (e.g., 'Abra', 'SmallRLGen9Beta', 'Minikazam')
        username: Unique username for this agent
        num_battles: Number of battles to play
    """
    print(f"\n{'='*70}")
    print(f"Starting {agent_name} as '{username}' on gen9randombattle")
    print(f"Target: {num_battles} battles")
    print(f"{'='*70}\n")

    # Get the pretrained model
    pretrained_model = get_pretrained_model(agent_name)

    # Initialize the agent
    agent = pretrained_model.initialize_agent(checkpoint=None, log=False)
    agent.env_mode = "sync"
    agent.parallel_actors = 1
    agent.verbose = True

    # Create the ladder environment for gen9randombattle
    # Note: Random battles don't use a team_set since teams are auto-generated by the server
    make_env = lambda: make_local_ladder_env(
        observation_space=pretrained_model.observation_space,
        action_space=pretrained_model.action_space,
        reward_function=pretrained_model.reward_function,
        num_battles=num_battles,
        player_username=username,
        player_avatar=None,  # Use default avatar
        player_team_set=None,  # No team set needed for random battles
        battle_backend="poke-env",
        battle_format="gen9randombattle",
        save_trajectories_to=None,
        save_team_results_to=None,
    )

    # Run the evaluation
    print("Agent initialized. Starting battles...\n")
    results = agent.evaluate_test(
        [make_env],
        timesteps=num_battles * 1000,
        episodes=num_battles,
    )

    print(f"\n{'='*70}")
    print(f"RESULTS for {username} ({agent_name}):")
    print(f"{'='*70}")
    print(results)
    print()

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Run a single RL agent on gen9randombattle ladder"
    )
    parser.add_argument(
        "--agent",
        type=str,
        default="Abra",
        choices=["Abra", "SmallRLGen9Beta", "Minikazam"],
        help="Pretrained model to use (must support Gen 9)"
    )
    parser.add_argument(
        "--username",
        type=str,
        required=True,
        help="Unique username for this agent on the ladder"
    )
    parser.add_argument(
        "--battles",
        type=int,
        default=20,
        help="Number of battles to play"
    )

    args = parser.parse_args()

    try:
        run_agent(
            agent_name=args.agent,
            username=args.username,
            num_battles=args.battles
        )
    except KeyboardInterrupt:
        print("\n\nAgent stopped by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\nError running agent: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
